[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mujahed"
authors = [{name = "Mujahed", email = "mujahed.mca@gmail.com"}]
dynamic = ["version", "description"]
